Completed Authentication Screens
Siduchels/7-day-Android-App-Challenge pull request #4
Opened 2024-08-24 18:51 UTC by aliarbaaz

# Pull Request

## Description

- Implemented the Start screen, Login screen and Signup screen UI.
- Added navigation functionality between the Start, Login and Signup screens.

## Checklist

- [ ] I have added a screenshot or screen recording showing the functionality of the app.
- [ ] I have tested the project and confirmed it works as expected.

## Screenshots

<img src="https://github.com/user-attachments/assets/c6fa7bd1-f487-4340-abbb-4b740bb7fbb9" alt="start screen" width="250"/>

<img src="https://github.com/user-attachments/assets/a84b2518-89eb-4634-9572-3002244a4f97" alt="login screen" width="250"/>

<img src="https://github.com/user-attachments/assets/000c081d-1bd3-42d8-bf31-3cea503d90f4" alt="login screen" width="250"/>

2024-08-24 18:59 UTC, Siduchels requested changes

2024-08-24 18:59 UTC, Siduchels commented on meal_mate/app/src/main/java/com/android/engineer/mealmate/view/features/auth/LoginScreen.kt
> +                            label = "Username",
@aliarbaaz Get this string from strings.xml

2024-08-24 18:59 UTC, Siduchels commented on meal_mate/app/src/main/java/com/android/engineer/mealmate/view/features/auth/SignupScreen.kt
> +                            label = "First Name",
Don't hard code the values.

2024-08-24 19:08 UTC, aliarbaaz commented on meal_mate/app/src/main/java/com/android/engineer/mealmate/view/features/auth/SignupScreen.kt
> +                            label = "First Name",
only label right?

2024-08-25 08:15 UTC, Siduchels commented on meal_mate/app/src/main/java/com/android/engineer/mealmate/view/features/auth/SignupScreen.kt
> +                            label = "First Name",
Yes @aliarbaaz only for label value.

2024-08-25 08:48 UTC, Siduchels approved these changes

2024-08-25 08:58 UTC, ZSank approved these changes

2024-08-25 08:58 UTC, merged